export type SeedDifficulty = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2'
export type SeedCategory =
  | 'Daily Words'
  | 'IELTS'
  | 'Business English'
  | 'Academic'
  | 'Travel'
  | 'Technology'

export interface SeedWord {
  word: string // ingliz so'z, kichik harf, BUTUN RO'YXAT BO'YICHA UNIKAL
  pronunciation?: string // IPA, masalan "/əˈbændən/"
  partOfSpeech?: string // "noun" | "verb" | "adjective" | "adverb" | "phrase" ...
  difficulty: SeedDifficulty
  category: SeedCategory
  uz: {
    translation: string // tabiiy o'zbekcha tarjima (lotin alifbosi)
    definitionEn?: string // sodda inglizcha ta'rif
    exampleEn?: string // tabiiy inglizcha misol gap
    exampleTranslated?: string // o'sha misolning o'zbekcha tarjimasi
  }
}

export const SEED_WORDS: SeedWord[] = [
  // ============================================================
  // DAILY WORDS — 30 ta (A1-A2) — bepul userlar uchun
  // ============================================================
  {
    word: 'family',
    pronunciation: '/ˈfæməli/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'oila',
      definitionEn: 'A group of people who are related to each other, such as parents and children.',
      exampleEn: 'My family has dinner together every evening.',
      exampleTranslated: 'Oilam har kuni kechqurun birga ovqatlanadi.',
    },
  },
  {
    word: 'water',
    pronunciation: '/ˈwɔːtər/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'suv',
      definitionEn: 'A clear liquid that has no colour or taste and that we drink.',
      exampleEn: 'Please give me a glass of water.',
      exampleTranslated: 'Iltimos, menga bir stakan suv bering.',
    },
  },
  {
    word: 'house',
    pronunciation: '/haʊs/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'uy',
      definitionEn: 'A building where people live.',
      exampleEn: 'They are building a new house near the river.',
      exampleTranslated: 'Ular daryo yonida yangi uy qurishyapti.',
    },
  },
  {
    word: 'friend',
    pronunciation: '/frend/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: "do'st",
      definitionEn: 'A person you know well and like, but who is not your relative.',
      exampleEn: 'My best friend lives in the same neighbourhood.',
      exampleTranslated: "Eng yaqin do'stim shu mahallada yashaydi.",
    },
  },
  {
    word: 'food',
    pronunciation: '/fuːd/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'ovqat',
      definitionEn: 'Things that people and animals eat.',
      exampleEn: 'The food at this restaurant is delicious.',
      exampleTranslated: 'Bu restorandagi ovqat juda mazali.',
    },
  },
  {
    word: 'work',
    pronunciation: '/wɜːrk/',
    partOfSpeech: 'verb',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'ishlamoq',
      definitionEn: 'To do a job, especially to earn money.',
      exampleEn: 'I work in an office from nine to six.',
      exampleTranslated: "Men ofisda to'qqizdan oltigacha ishlayman.",
    },
  },
  {
    word: 'school',
    pronunciation: '/skuːl/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'maktab',
      definitionEn: 'A place where children go to learn.',
      exampleEn: 'The children walk to school every morning.',
      exampleTranslated: 'Bolalar har kuni ertalab piyoda maktabga borishadi.',
    },
  },
  {
    word: 'book',
    pronunciation: '/bʊk/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'kitob',
      definitionEn: 'A set of printed pages held together inside a cover.',
      exampleEn: 'She is reading an interesting book about history.',
      exampleTranslated: "U tarix haqidagi qiziqarli kitobni o'qiyapti.",
    },
  },
  {
    word: 'money',
    pronunciation: '/ˈmʌni/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'pul',
      definitionEn: 'Coins and notes that people use to buy things.',
      exampleEn: 'I need to save money for a new phone.',
      exampleTranslated: "Yangi telefon uchun pul yig'ishim kerak.",
    },
  },
  {
    word: 'time',
    pronunciation: '/taɪm/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'vaqt',
      definitionEn: 'The thing that is measured in minutes, hours, days and years.',
      exampleEn: 'We do not have much time before the train leaves.',
      exampleTranslated: "Poyezd jo'nashidan oldin ko'p vaqtimiz qolmadi.",
    },
  },
  {
    word: 'morning',
    pronunciation: '/ˈmɔːrnɪŋ/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'ertalab',
      definitionEn: 'The early part of the day, from when the sun rises until midday.',
      exampleEn: 'I drink a cup of tea every morning.',
      exampleTranslated: 'Men har kuni ertalab bir piyola choy ichaman.',
    },
  },
  {
    word: 'happy',
    pronunciation: '/ˈhæpi/',
    partOfSpeech: 'adjective',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'baxtli',
      definitionEn: 'Feeling pleased and satisfied.',
      exampleEn: 'She was very happy to see her old friends.',
      exampleTranslated: "U eski do'stlarini ko'rib juda baxtli bo'ldi.",
    },
  },
  {
    word: 'help',
    pronunciation: '/help/',
    partOfSpeech: 'verb',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'yordam bermoq',
      definitionEn: 'To do something that makes things easier for someone.',
      exampleEn: 'Can you help me carry these bags?',
      exampleTranslated: "Bu sumkalarni ko'tarishga yordam bera olasizmi?",
    },
  },
  {
    word: 'buy',
    pronunciation: '/baɪ/',
    partOfSpeech: 'verb',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'sotib olmoq',
      definitionEn: 'To get something by paying money for it.',
      exampleEn: 'I want to buy some bread from the bakery.',
      exampleTranslated: "Men nonvoyxonadan biroz non sotib olmoqchiman.",
    },
  },
  {
    word: 'eat',
    pronunciation: '/iːt/',
    partOfSpeech: 'verb',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'yemoq',
      definitionEn: 'To put food in your mouth and swallow it.',
      exampleEn: 'We usually eat lunch at one o\'clock.',
      exampleTranslated: 'Biz odatda soat birda tushlik qilamiz.',
    },
  },
  {
    word: 'sleep',
    pronunciation: '/sliːp/',
    partOfSpeech: 'verb',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'uxlamoq',
      definitionEn: 'To rest with your eyes closed and your mind not working.',
      exampleEn: 'Children need to sleep at least eight hours.',
      exampleTranslated: 'Bolalar kamida sakkiz soat uxlashi kerak.',
    },
  },
  {
    word: 'street',
    pronunciation: '/striːt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: "ko'cha",
      definitionEn: 'A road in a town or city with houses and buildings on the sides.',
      exampleEn: 'There is a small shop at the end of our street.',
      exampleTranslated: "Ko'chamizning oxirida kichik do'kon bor.",
    },
  },
  {
    word: 'weather',
    pronunciation: '/ˈweðər/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'ob-havo',
      definitionEn: 'The condition of the air outside, such as rain, sun or wind.',
      exampleEn: 'The weather is very hot in summer here.',
      exampleTranslated: 'Bu yerda yozda ob-havo juda issiq.',
    },
  },
  {
    word: 'busy',
    pronunciation: '/ˈbɪzi/',
    partOfSpeech: 'adjective',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'band',
      definitionEn: 'Having a lot of things to do.',
      exampleEn: 'I am too busy to talk right now.',
      exampleTranslated: 'Hozir gaplashishga juda bandman.',
    },
  },
  {
    word: 'tired',
    pronunciation: '/ˈtaɪərd/',
    partOfSpeech: 'adjective',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'charchagan',
      definitionEn: 'Feeling that you need to rest or sleep.',
      exampleEn: 'He felt tired after the long journey.',
      exampleTranslated: "U uzoq safardan keyin o'zini charchagan his qildi.",
    },
  },
  {
    word: 'clean',
    pronunciation: '/kliːn/',
    partOfSpeech: 'adjective',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'toza',
      definitionEn: 'Not dirty; free from dust and marks.',
      exampleEn: 'Please keep your room clean and tidy.',
      exampleTranslated: 'Iltimos, xonangizni toza va tartibli saqlang.',
    },
  },
  {
    word: 'late',
    pronunciation: '/leɪt/',
    partOfSpeech: 'adjective',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'kech',
      definitionEn: 'Arriving or happening after the expected time.',
      exampleEn: 'Sorry, I am late because of the traffic.',
      exampleTranslated: 'Kechirasiz, tirbandlik tufayli kechikdim.',
    },
  },
  {
    word: 'remember',
    pronunciation: '/rɪˈmembər/',
    partOfSpeech: 'verb',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'eslamoq',
      definitionEn: 'To keep something in your mind or bring it back to your mind.',
      exampleEn: 'I cannot remember where I left my keys.',
      exampleTranslated: "Kalitlarimni qayerga qoldirganimni eslay olmayapman.",
    },
  },
  {
    word: 'understand',
    pronunciation: '/ˌʌndərˈstænd/',
    partOfSpeech: 'verb',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'tushunmoq',
      definitionEn: 'To know the meaning of something.',
      exampleEn: 'Do you understand the question?',
      exampleTranslated: 'Savolni tushunyapsizmi?',
    },
  },
  {
    word: 'neighbour',
    pronunciation: '/ˈneɪbər/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'qo\'shni',
      definitionEn: 'A person who lives near you.',
      exampleEn: 'Our neighbour invited us for tea.',
      exampleTranslated: "Qo'shnimiz bizni choyga taklif qildi.",
    },
  },
  {
    word: 'market',
    pronunciation: '/ˈmɑːrkɪt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'bozor',
      definitionEn: 'A place where people buy and sell food and other goods.',
      exampleEn: 'My mother buys fresh vegetables at the market.',
      exampleTranslated: 'Onam bozordan yangi sabzavotlar sotib oladi.',
    },
  },
  {
    word: 'guest',
    pronunciation: '/ɡest/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'mehmon',
      definitionEn: 'A person who is invited to your home or to an event.',
      exampleEn: 'We are expecting guests this weekend.',
      exampleTranslated: 'Bu hafta oxiri mehmonlar kutyapmiz.',
    },
  },
  {
    word: 'borrow',
    pronunciation: '/ˈbɑːroʊ/',
    partOfSpeech: 'verb',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'qarz olmoq',
      definitionEn: 'To take something from someone and give it back later.',
      exampleEn: 'Can I borrow your pen for a moment?',
      exampleTranslated: "Bir lahzaga ruchkangizni olib tursam bo'ladimi?",
    },
  },
  {
    word: 'kitchen',
    pronunciation: '/ˈkɪtʃɪn/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Daily Words',
    uz: {
      translation: 'oshxona',
      definitionEn: 'A room where food is prepared and cooked.',
      exampleEn: 'She is cooking dinner in the kitchen.',
      exampleTranslated: 'U oshxonada kechki ovqat tayyorlayapti.',
    },
  },
  {
    word: 'weekend',
    pronunciation: '/ˈwiːkend/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Daily Words',
    uz: {
      translation: 'dam olish kunlari',
      definitionEn: 'Saturday and Sunday, when most people do not work.',
      exampleEn: 'We often visit our relatives at the weekend.',
      exampleTranslated: 'Biz dam olish kunlari ko\'pincha qarindoshlarimiznikiga boramiz.',
    },
  },

  // ============================================================
  // TRAVEL — 25 ta (A1-B1)
  // ============================================================
  {
    word: 'airport',
    pronunciation: '/ˈeərpɔːrt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'aeroport',
      definitionEn: 'A place where planes take off and land.',
      exampleEn: 'We arrived at the airport two hours before the flight.',
      exampleTranslated: 'Biz aeroportga parvozdan ikki soat oldin yetib keldik.',
    },
  },
  {
    word: 'ticket',
    pronunciation: '/ˈtɪkɪt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'chipta',
      definitionEn: 'A small piece of paper that shows you have paid to travel or enter.',
      exampleEn: 'I bought a return ticket to Tashkent.',
      exampleTranslated: "Men Toshkentga borib-kelish chiptasini sotib oldim.",
    },
  },
  {
    word: 'passport',
    pronunciation: '/ˈpæspɔːrt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'pasport',
      definitionEn: 'An official document that allows you to travel to other countries.',
      exampleEn: 'Do not forget your passport at the hotel.',
      exampleTranslated: 'Pasportingizni mehmonxonada unutib qoldirmang.',
    },
  },
  {
    word: 'luggage',
    pronunciation: '/ˈlʌɡɪdʒ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'yuk, bagaj',
      definitionEn: 'The bags and suitcases you take with you when you travel.',
      exampleEn: 'My luggage was too heavy to carry alone.',
      exampleTranslated: "Yukim yolg'iz ko'tarish uchun juda og'ir edi.",
    },
  },
  {
    word: 'flight',
    pronunciation: '/flaɪt/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'parvoz',
      definitionEn: 'A journey made by air in a plane.',
      exampleEn: 'Our flight to Dubai was delayed by an hour.',
      exampleTranslated: "Dubayga parvozimiz bir soatga kechiktirildi.",
    },
  },
  {
    word: 'hotel',
    pronunciation: '/hoʊˈtel/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Travel',
    uz: {
      translation: 'mehmonxona',
      definitionEn: 'A building where you pay to sleep and eat when you travel.',
      exampleEn: 'We stayed at a small hotel in the city centre.',
      exampleTranslated: 'Biz shahar markazidagi kichik mehmonxonada turdik.',
    },
  },
  {
    word: 'reservation',
    pronunciation: '/ˌrezərˈveɪʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'bron, oldindan buyurtma',
      definitionEn: 'An arrangement to keep a room or seat for you in advance.',
      exampleEn: 'I made a reservation for two nights.',
      exampleTranslated: 'Men ikki kechaga bron qildim.',
    },
  },
  {
    word: 'journey',
    pronunciation: '/ˈdʒɜːrni/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'sayohat, safar',
      definitionEn: 'An act of travelling from one place to another, especially over a long distance.',
      exampleEn: 'The journey from Samarkand to Bukhara takes a few hours.',
      exampleTranslated: "Samarqanddan Buxorogacha bo'lgan safar bir necha soat davom etadi.",
    },
  },
  {
    word: 'destination',
    pronunciation: '/ˌdestɪˈneɪʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'manzil, boriladigan joy',
      definitionEn: 'The place where someone or something is going.',
      exampleEn: 'Our final destination was a small village in the mountains.',
      exampleTranslated: "Bizning oxirgi manzilimiz tog'lardagi kichik qishloq edi.",
    },
  },
  {
    word: 'arrive',
    pronunciation: '/əˈraɪv/',
    partOfSpeech: 'verb',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'yetib kelmoq',
      definitionEn: 'To get to a place at the end of a journey.',
      exampleEn: 'We will arrive in the city by evening.',
      exampleTranslated: 'Biz kechgacha shaharga yetib boramiz.',
    },
  },
  {
    word: 'depart',
    pronunciation: '/dɪˈpɑːrt/',
    partOfSpeech: 'verb',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: "jo'namoq, ketmoq",
      definitionEn: 'To leave a place, especially to start a journey.',
      exampleEn: 'The train departs from platform three.',
      exampleTranslated: "Poyezd uchinchi perrondan jo'naydi.",
    },
  },
  {
    word: 'abroad',
    pronunciation: '/əˈbrɔːd/',
    partOfSpeech: 'adverb',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'chet elga, chet elda',
      definitionEn: 'In or to a foreign country.',
      exampleEn: 'Many young people want to study abroad.',
      exampleTranslated: "Ko'plab yoshlar chet elda o'qishni xohlaydi.",
    },
  },
  {
    word: 'tourist',
    pronunciation: '/ˈtʊrɪst/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'sayyoh, turist',
      definitionEn: 'A person who travels and visits places for pleasure.',
      exampleEn: 'Many tourists visit the old city of Khiva.',
      exampleTranslated: "Ko'plab sayyohlar qadimiy Xiva shahriga tashrif buyuradi.",
    },
  },
  {
    word: 'suitcase',
    pronunciation: '/ˈsuːtkeɪs/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Travel',
    uz: {
      translation: 'chamadon',
      definitionEn: 'A large bag with flat sides for carrying clothes when you travel.',
      exampleEn: 'I packed my suitcase the night before the trip.',
      exampleTranslated: 'Safardan oldingi kechasi chamadonimni yig\'dim.',
    },
  },
  {
    word: 'map',
    pronunciation: '/mæp/',
    partOfSpeech: 'noun',
    difficulty: 'A1',
    category: 'Travel',
    uz: {
      translation: 'xarita',
      definitionEn: 'A drawing of an area that shows roads, rivers and cities.',
      exampleEn: 'We used a map to find the museum.',
      exampleTranslated: 'Muzeyni topish uchun xaritadan foydalandik.',
    },
  },
  {
    word: 'guide',
    pronunciation: '/ɡaɪd/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'gid, yo\'lboshchi',
      definitionEn: 'A person who shows tourists around a place.',
      exampleEn: 'The guide told us many stories about the city.',
      exampleTranslated: "Gid bizga shahar haqida ko'plab voqealar aytib berdi.",
    },
  },
  {
    word: 'currency',
    pronunciation: '/ˈkɜːrənsi/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'valyuta, pul birligi',
      definitionEn: 'The money used in a particular country.',
      exampleEn: 'You should exchange your currency at the airport.',
      exampleTranslated: 'Valyutangizni aeroportda almashtirishingiz kerak.',
    },
  },
  {
    word: 'delay',
    pronunciation: '/dɪˈleɪ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'kechikish',
      definitionEn: 'A situation in which something happens later than planned.',
      exampleEn: 'There was a long delay because of bad weather.',
      exampleTranslated: "Yomon ob-havo tufayli uzoq kechikish bo'ldi.",
    },
  },
  {
    word: 'boarding',
    pronunciation: '/ˈbɔːrdɪŋ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: "samolyotga chiqish, o'tirish",
      definitionEn: 'The act of getting on a plane, ship or train.',
      exampleEn: 'Boarding for our flight will begin in ten minutes.',
      exampleTranslated: "Parvozimizga chiqish o'n daqiqadan keyin boshlanadi.",
    },
  },
  {
    word: 'customs',
    pronunciation: '/ˈkʌstəmz/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'bojxona',
      definitionEn: 'The place at a border where officials check your bags.',
      exampleEn: 'We had to wait at customs for a while.',
      exampleTranslated: "Bojxonada bir oz kutishimizga to'g'ri keldi.",
    },
  },
  {
    word: 'sightseeing',
    pronunciation: '/ˈsaɪtsiːɪŋ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'diqqatga sazovor joylarni tomosha qilish',
      definitionEn: 'The activity of visiting interesting places as a tourist.',
      exampleEn: 'We spent the whole day sightseeing in the old town.',
      exampleTranslated: "Biz kun bo'yi eski shaharning diqqatga sazovor joylarini tomosha qildik.",
    },
  },
  {
    word: 'route',
    pronunciation: '/ruːt/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: "yo'nalish, marshrut",
      definitionEn: 'The way you take to get from one place to another.',
      exampleEn: 'The driver knew a faster route to the station.',
      exampleTranslated: "Haydovchi bekatgacha tezroq yo'nalishni bilardi.",
    },
  },
  {
    word: 'departure',
    pronunciation: '/dɪˈpɑːrtʃər/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: "jo'nash, ketish",
      definitionEn: 'The act of leaving a place, especially to start a journey.',
      exampleEn: 'The departure time is printed on your ticket.',
      exampleTranslated: "Jo'nash vaqti chiptangizda yozilgan.",
    },
  },
  {
    word: 'accommodation',
    pronunciation: '/əˌkɑːməˈdeɪʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'turar joy, yashash joyi',
      definitionEn: 'A place where you live or stay, especially while travelling.',
      exampleEn: 'The price includes flights and accommodation.',
      exampleTranslated: 'Narx parvozlar va turar joyni o\'z ichiga oladi.',
    },
  },
  {
    word: 'souvenir',
    pronunciation: '/ˌsuːvəˈnɪr/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Travel',
    uz: {
      translation: 'esdalik sovg\'asi',
      definitionEn: 'A thing you buy or keep to remember a place or event.',
      exampleEn: 'I bought a small souvenir for my sister.',
      exampleTranslated: 'Singlimga kichik esdalik sovg\'asi sotib oldim.',
    },
  },

  // ============================================================
  // TECHNOLOGY — 25 ta (A2-B2)
  // ============================================================
  {
    word: 'computer',
    pronunciation: '/kəmˈpjuːtər/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'kompyuter',
      definitionEn: 'An electronic machine that stores and works with information.',
      exampleEn: 'He uses his computer for work and study.',
      exampleTranslated: "U kompyuteridan ish va o'qish uchun foydalanadi.",
    },
  },
  {
    word: 'internet',
    pronunciation: '/ˈɪntərnet/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'internet',
      definitionEn: 'The large system that connects computers around the world.',
      exampleEn: 'I found the answer on the internet.',
      exampleTranslated: 'Javobni internetdan topdim.',
    },
  },
  {
    word: 'phone',
    pronunciation: '/foʊn/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'telefon',
      definitionEn: 'A device used to talk to people who are far away.',
      exampleEn: 'My phone battery is almost empty.',
      exampleTranslated: "Telefonim batareyasi deyarli tugadi.",
    },
  },
  {
    word: 'screen',
    pronunciation: '/skriːn/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'ekran',
      definitionEn: 'The flat surface of a device where you see pictures and text.',
      exampleEn: 'The text is too small to read on this screen.',
      exampleTranslated: "Matn bu ekranda o'qish uchun juda kichik.",
    },
  },
  {
    word: 'software',
    pronunciation: '/ˈsɔːftweər/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: "dasturiy ta'minot (software)",
      definitionEn: 'The programs that tell a computer what to do.',
      exampleEn: 'We need to update the software on all computers.',
      exampleTranslated: "Barcha kompyuterlardagi dasturiy ta'minotni yangilashimiz kerak.",
    },
  },
  {
    word: 'download',
    pronunciation: '/ˌdaʊnˈloʊd/',
    partOfSpeech: 'verb',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'yuklab olmoq',
      definitionEn: 'To copy a file from the internet to your device.',
      exampleEn: 'You can download the app for free.',
      exampleTranslated: 'Ilovani bepul yuklab olishingiz mumkin.',
    },
  },
  {
    word: 'password',
    pronunciation: '/ˈpæswɜːrd/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'parol',
      definitionEn: 'A secret word or numbers that let you use a device or account.',
      exampleEn: 'Please choose a strong password for your account.',
      exampleTranslated: 'Hisobingiz uchun kuchli parol tanlang.',
    },
  },
  {
    word: 'keyboard',
    pronunciation: '/ˈkiːbɔːrd/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'klaviatura',
      definitionEn: 'The set of keys you press to type on a computer.',
      exampleEn: 'I spilled water on my keyboard.',
      exampleTranslated: "Klaviaturamga suv to'kib yubordim.",
    },
  },
  {
    word: 'file',
    pronunciation: '/faɪl/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Technology',
    uz: {
      translation: 'fayl',
      definitionEn: 'A collection of information stored on a computer with one name.',
      exampleEn: 'Please send me the file by email.',
      exampleTranslated: 'Iltimos, faylni menga elektron pochta orqali yuboring.',
    },
  },
  {
    word: 'application',
    pronunciation: '/ˌæplɪˈkeɪʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'ilova (application)',
      definitionEn: 'A program that you use on a phone or computer for a task.',
      exampleEn: 'This application helps you learn new words.',
      exampleTranslated: "Bu ilova sizga yangi so'zlarni o'rganishga yordam beradi.",
    },
  },
  {
    word: 'device',
    pronunciation: '/dɪˈvaɪs/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'qurilma',
      definitionEn: 'A machine or piece of equipment made for a special purpose.',
      exampleEn: 'You can open this website on any device.',
      exampleTranslated: "Bu veb-saytni istalgan qurilmada ochishingiz mumkin.",
    },
  },
  {
    word: 'network',
    pronunciation: '/ˈnetwɜːrk/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'tarmoq',
      definitionEn: 'A group of computers or devices connected together.',
      exampleEn: 'The office network is very fast.',
      exampleTranslated: 'Ofis tarmog\'i juda tez.',
    },
  },
  {
    word: 'update',
    pronunciation: '/ˌʌpˈdeɪt/',
    partOfSpeech: 'verb',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'yangilamoq',
      definitionEn: 'To make something more modern by adding new information or features.',
      exampleEn: 'Remember to update your apps regularly.',
      exampleTranslated: 'Ilovalaringizni muntazam yangilashni unutmang.',
    },
  },
  {
    word: 'browser',
    pronunciation: '/ˈbraʊzər/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'brauzer',
      definitionEn: 'A program that lets you look at websites on the internet.',
      exampleEn: 'Open the link in a different browser.',
      exampleTranslated: 'Havolani boshqa brauzerda oching.',
    },
  },
  {
    word: 'data',
    pronunciation: '/ˈdeɪtə/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: "ma'lumotlar",
      definitionEn: 'Facts or information, especially when stored by a computer.',
      exampleEn: 'The company keeps all customer data safe.',
      exampleTranslated: "Kompaniya barcha mijoz ma'lumotlarini xavfsiz saqlaydi.",
    },
  },
  {
    word: 'upload',
    pronunciation: '/ˌʌpˈloʊd/',
    partOfSpeech: 'verb',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'yuklamoq, joylamoq',
      definitionEn: 'To copy a file from your device to the internet.',
      exampleEn: 'She uploaded the photos to the website.',
      exampleTranslated: 'U rasmlarni veb-saytga yukladi.',
    },
  },
  {
    word: 'wireless',
    pronunciation: '/ˈwaɪərləs/',
    partOfSpeech: 'adjective',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'simsiz',
      definitionEn: 'Working without wires, using radio signals.',
      exampleEn: 'The café offers free wireless internet.',
      exampleTranslated: 'Kafe bepul simsiz internet taklif qiladi.',
    },
  },
  {
    word: 'install',
    pronunciation: '/ɪnˈstɔːl/',
    partOfSpeech: 'verb',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: "o'rnatmoq",
      definitionEn: 'To put a program onto a computer so that it is ready to use.',
      exampleEn: 'You need to install this program before the meeting.',
      exampleTranslated: "Bu dasturni uchrashuvdan oldin o'rnatishingiz kerak.",
    },
  },
  {
    word: 'interface',
    pronunciation: '/ˈɪntərfeɪs/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: 'interfeys',
      definitionEn: 'The way a program looks and how the user controls it.',
      exampleEn: 'The new app has a simple and clean interface.',
      exampleTranslated: 'Yangi ilovaning interfeysi sodda va toza.',
    },
  },
  {
    word: 'algorithm',
    pronunciation: '/ˈælɡərɪðəm/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: 'algoritm',
      definitionEn: 'A set of steps a computer follows to solve a problem.',
      exampleEn: 'The search algorithm finds results in seconds.',
      exampleTranslated: 'Qidiruv algoritmi natijalarni soniyalar ichida topadi.',
    },
  },
  {
    word: 'database',
    pronunciation: '/ˈdeɪtəbeɪs/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: "ma'lumotlar bazasi",
      definitionEn: 'A large amount of information stored in a computer system.',
      exampleEn: 'All user accounts are kept in one database.',
      exampleTranslated: "Barcha foydalanuvchi hisoblari bitta ma'lumotlar bazasida saqlanadi.",
    },
  },
  {
    word: 'deploy',
    pronunciation: '/dɪˈplɔɪ/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: 'joriy qilmoq, ishga tushirmoq',
      definitionEn: 'To make software available and ready for people to use.',
      exampleEn: 'The team will deploy the new version tonight.',
      exampleTranslated: 'Jamoa yangi versiyani bugun kechqurun ishga tushiradi.',
    },
  },
  {
    word: 'encryption',
    pronunciation: '/ɪnˈkrɪpʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: 'shifrlash',
      definitionEn: 'The process of changing information into a secret code to keep it safe.',
      exampleEn: 'Encryption protects your messages from hackers.',
      exampleTranslated: 'Shifrlash xabarlaringizni xakerlardan himoya qiladi.',
    },
  },
  {
    word: 'bug',
    pronunciation: '/bʌɡ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Technology',
    uz: {
      translation: 'xatolik (dasturdagi)',
      definitionEn: 'A mistake or fault in a computer program.',
      exampleEn: 'The developers fixed the bug in the latest update.',
      exampleTranslated: "Dasturchilar so'nggi yangilanishda xatolikni tuzatishdi.",
    },
  },
  {
    word: 'server',
    pronunciation: '/ˈsɜːrvər/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Technology',
    uz: {
      translation: 'server',
      definitionEn: 'A powerful computer that stores data and serves it to other computers.',
      exampleEn: 'The website was slow because the server was busy.',
      exampleTranslated: 'Server band bo\'lgani uchun veb-sayt sekin ishladi.',
    },
  },

  // ============================================================
  // IELTS — 35 ta (B2-C1) — eng katta segment
  // ============================================================
  {
    word: 'significant',
    pronunciation: '/sɪɡˈnɪfɪkənt/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'muhim, sezilarli',
      definitionEn: 'Large or important enough to be noticed or to have an effect.',
      exampleEn: 'There has been a significant increase in tourism.',
      exampleTranslated: "Turizmda sezilarli o'sish kuzatildi.",
    },
  },
  {
    word: 'consequently',
    pronunciation: '/ˈkɑːnsɪkwentli/',
    partOfSpeech: 'adverb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'natijada, shu sababli',
      definitionEn: 'As a result of something that happened before.',
      exampleEn: 'Prices rose, and consequently, fewer people travelled.',
      exampleTranslated: "Narxlar oshdi va natijada kamroq odam sayohat qildi.",
    },
  },
  {
    word: 'demonstrate',
    pronunciation: '/ˈdemənstreɪt/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "ko'rsatmoq, namoyish etmoq",
      definitionEn: 'To show clearly that something is true or exists.',
      exampleEn: 'The study demonstrates the benefits of regular exercise.',
      exampleTranslated: "Tadqiqot muntazam mashqlarning foydasini ko'rsatadi.",
    },
  },
  {
    word: 'substantial',
    pronunciation: '/səbˈstænʃl/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'salmoqli, katta',
      definitionEn: 'Large in amount, value or importance.',
      exampleEn: 'The government made a substantial investment in education.',
      exampleTranslated: "Hukumat ta'limga salmoqli sarmoya kiritdi.",
    },
  },
  {
    word: 'phenomenon',
    pronunciation: '/fəˈnɑːmɪnən/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'hodisa',
      definitionEn: 'A fact or situation that exists and can be observed.',
      exampleEn: 'Climate change is a global phenomenon.',
      exampleTranslated: "Iqlim o'zgarishi global hodisadir.",
    },
  },
  {
    word: 'contribute',
    pronunciation: '/kənˈtrɪbjuːt/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "hissa qo'shmoq",
      definitionEn: 'To help to make something happen or to give part of the total.',
      exampleEn: 'Volunteers contribute a lot to their communities.',
      exampleTranslated: "Ko'ngillilar o'z jamiyatlariga katta hissa qo'shadi.",
    },
  },
  {
    word: 'tendency',
    pronunciation: '/ˈtendənsi/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'moyillik, tendentsiya',
      definitionEn: 'A way that a person or thing usually behaves; a general direction.',
      exampleEn: 'There is a growing tendency to work from home.',
      exampleTranslated: "Uydan ishlashga moyillik kuchayib bormoqda.",
    },
  },
  {
    word: 'inevitable',
    pronunciation: '/ɪnˈevɪtəbl/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: "muqarrar, oldini olib bo'lmaydigan",
      definitionEn: 'Certain to happen and impossible to avoid.',
      exampleEn: 'Some changes in society are inevitable.',
      exampleTranslated: "Jamiyatdagi ba'zi o'zgarishlar muqarrardir.",
    },
  },
  {
    word: 'beneficial',
    pronunciation: '/ˌbenɪˈfɪʃl/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'foydali',
      definitionEn: 'Having a good or helpful effect.',
      exampleEn: 'Reading regularly is beneficial for children.',
      exampleTranslated: "Muntazam o'qish bolalar uchun foydali.",
    },
  },
  {
    word: 'crucial',
    pronunciation: '/ˈkruːʃl/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'hal qiluvchi, juda muhim',
      definitionEn: 'Extremely important because it affects the result of something.',
      exampleEn: 'Education plays a crucial role in development.',
      exampleTranslated: "Ta'lim rivojlanishda hal qiluvchi rol o'ynaydi.",
    },
  },
  {
    word: 'enhance',
    pronunciation: '/ɪnˈhæns/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'yaxshilamoq, oshirmoq',
      definitionEn: 'To improve the quality, amount or value of something.',
      exampleEn: 'Technology can enhance the learning experience.',
      exampleTranslated: "Texnologiya o'qish jarayonini yaxshilashi mumkin.",
    },
  },
  {
    word: 'diverse',
    pronunciation: '/daɪˈvɜːrs/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'xilma-xil, rang-barang',
      definitionEn: 'Including many different types of people or things.',
      exampleEn: 'The city has a diverse population from many countries.',
      exampleTranslated: "Shaharda ko'plab davlatlardan kelgan xilma-xil aholi yashaydi.",
    },
  },
  {
    word: 'acquire',
    pronunciation: '/əˈkwaɪər/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'egallamoq, orttirmoq',
      definitionEn: 'To get or gain something, such as a skill or knowledge.',
      exampleEn: 'Students acquire new skills through practice.',
      exampleTranslated: "O'quvchilar amaliyot orqali yangi ko'nikmalarni egallaydi.",
    },
  },
  {
    word: 'sufficient',
    pronunciation: '/səˈfɪʃnt/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'yetarli',
      definitionEn: 'As much as is needed for a particular purpose.',
      exampleEn: 'There was sufficient evidence to support the claim.',
      exampleTranslated: "Da'voni qo'llab-quvvatlash uchun yetarli dalil bor edi.",
    },
  },
  {
    word: 'prominent',
    pronunciation: '/ˈprɑːmɪnənt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'taniqli, mashhur',
      definitionEn: 'Important and well known.',
      exampleEn: 'She is a prominent scientist in her field.',
      exampleTranslated: "U o'z sohasidagi taniqli olima.",
    },
  },
  {
    word: 'reluctant',
    pronunciation: '/rɪˈlʌktənt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'istamaydigan, ikkilanadigan',
      definitionEn: 'Not wanting to do something and therefore slow to do it.',
      exampleEn: 'Many people are reluctant to change their habits.',
      exampleTranslated: "Ko'p odamlar o'z odatlarini o'zgartirishni istamaydi.",
    },
  },
  {
    word: 'widespread',
    pronunciation: '/ˈwaɪdspred/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'keng tarqalgan',
      definitionEn: 'Existing or happening in many places or among many people.',
      exampleEn: 'The use of smartphones is now widespread.',
      exampleTranslated: 'Smartfonlardan foydalanish hozir keng tarqalgan.',
    },
  },
  {
    word: 'emphasis',
    pronunciation: '/ˈemfəsɪs/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: "urg'u, e'tibor",
      definitionEn: 'Special importance or attention given to something.',
      exampleEn: 'The school places great emphasis on creativity.',
      exampleTranslated: "Maktab ijodkorlikka katta e'tibor beradi.",
    },
  },
  {
    word: 'undertake',
    pronunciation: '/ˌʌndərˈteɪk/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: "zimmasiga olmoq, kirishmoq",
      definitionEn: 'To start to do something, especially something difficult or important.',
      exampleEn: 'The researchers undertook a detailed study of the issue.',
      exampleTranslated: "Tadqiqotchilar masala bo'yicha batafsil tadqiqotni zimmalariga olishdi.",
    },
  },
  {
    word: 'adequate',
    pronunciation: '/ˈædɪkwət/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "yetarli, maqbul",
      definitionEn: 'Good enough or large enough for a particular purpose.',
      exampleEn: 'The room was adequate for a small meeting.',
      exampleTranslated: 'Xona kichik uchrashuv uchun yetarli edi.',
    },
  },
  {
    word: 'illustrate',
    pronunciation: '/ˈɪləstreɪt/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'misol bilan tushuntirmoq, yoritmoq',
      definitionEn: 'To make something clear by giving examples.',
      exampleEn: 'This graph illustrates the change in temperature.',
      exampleTranslated: "Bu grafik harorat o'zgarishini yoritib beradi.",
    },
  },
  {
    word: 'comprehensive',
    pronunciation: '/ˌkɑːmprɪˈhensɪv/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'keng qamrovli, har tomonlama',
      definitionEn: 'Including all or nearly all the necessary parts or details.',
      exampleEn: 'The report gives a comprehensive overview of the economy.',
      exampleTranslated: 'Hisobot iqtisodiyotning keng qamrovli sharhini beradi.',
    },
  },
  {
    word: 'arise',
    pronunciation: '/əˈraɪz/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'yuzaga kelmoq, paydo bo\'lmoq',
      definitionEn: 'To happen or to begin to exist, especially a problem.',
      exampleEn: 'Several problems arose during the project.',
      exampleTranslated: 'Loyiha davomida bir nechta muammolar yuzaga keldi.',
    },
  },
  {
    word: 'estimate',
    pronunciation: '/ˈestɪmeɪt/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'taxmin qilmoq, baholamoq',
      definitionEn: 'To guess the size, amount or cost of something.',
      exampleEn: 'Experts estimate that the population will double.',
      exampleTranslated: 'Mutaxassislar aholi ikki barobar ortadi deb taxmin qilishyapti.',
    },
  },
  {
    word: 'majority',
    pronunciation: '/məˈdʒɔːrəti/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "ko'pchilik",
      definitionEn: 'More than half of a group of people or things.',
      exampleEn: 'The majority of students passed the exam.',
      exampleTranslated: "O'quvchilarning ko'pchiligi imtihondan o'tdi.",
    },
  },
  {
    word: 'gradually',
    pronunciation: '/ˈɡrædʒuəli/',
    partOfSpeech: 'adverb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'asta-sekin',
      definitionEn: 'Slowly, over a long period of time.',
      exampleEn: 'The weather gradually became warmer.',
      exampleTranslated: 'Ob-havo asta-sekin issiqlashdi.',
    },
  },
  {
    word: 'reduction',
    pronunciation: '/rɪˈdʌkʃn/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'kamayish, qisqartirish',
      definitionEn: 'The act of making something smaller in size or amount.',
      exampleEn: 'There was a sharp reduction in air pollution.',
      exampleTranslated: 'Havoning ifloslanishida keskin kamayish kuzatildi.',
    },
  },
  {
    word: 'alternative',
    pronunciation: '/ɔːlˈtɜːrnətɪv/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'muqobil, boshqa yo\'l',
      definitionEn: 'One of two or more things you can choose between.',
      exampleEn: 'Solar power is a clean alternative to coal.',
      exampleTranslated: "Quyosh energiyasi ko'mirga toza muqobildir.",
    },
  },
  {
    word: 'consume',
    pronunciation: '/kənˈsuːm/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "iste'mol qilmoq",
      definitionEn: 'To use or eat and drink something.',
      exampleEn: 'People consume more energy in winter.',
      exampleTranslated: "Odamlar qishda ko'proq energiya iste'mol qiladi.",
    },
  },
  {
    word: 'distinct',
    pronunciation: '/dɪˈstɪŋkt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'aniq, alohida, farqli',
      definitionEn: 'Clearly different or separate from others.',
      exampleEn: 'Each region has its own distinct culture.',
      exampleTranslated: "Har bir hududning o'ziga xos alohida madaniyati bor.",
    },
  },
  {
    word: 'overcome',
    pronunciation: '/ˌoʊvərˈkʌm/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: 'yengmoq, bartaraf etmoq',
      definitionEn: 'To succeed in dealing with a problem or difficulty.',
      exampleEn: 'She worked hard to overcome her fear of speaking.',
      exampleTranslated: "U gapirishdan qo'rquvini yengish uchun ko'p harakat qildi.",
    },
  },
  {
    word: 'numerous',
    pronunciation: '/ˈnuːmərəs/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'IELTS',
    uz: {
      translation: "ko'p sonli, ko'plab",
      definitionEn: 'Existing in large numbers; many.',
      exampleEn: 'There are numerous reasons to learn a new language.',
      exampleTranslated: "Yangi til o'rganishning ko'plab sabablari bor.",
    },
  },
  {
    word: 'evident',
    pronunciation: '/ˈevɪdənt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: "ravshan, aniq ko'rinib turgan",
      definitionEn: 'Easy to see or understand; clear.',
      exampleEn: 'It is evident that the plan needs improvement.',
      exampleTranslated: "Reja yaxshilanishi kerakligi aniq ko'rinib turibdi.",
    },
  },
  {
    word: 'considerable',
    pronunciation: '/kənˈsɪdərəbl/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: "anchagina, e'tiborli darajada",
      definitionEn: 'Great in amount, size or importance.',
      exampleEn: 'The project required a considerable amount of money.',
      exampleTranslated: "Loyiha anchagina mablag' talab qildi.",
    },
  },
  {
    word: 'facilitate',
    pronunciation: '/fəˈsɪlɪteɪt/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'IELTS',
    uz: {
      translation: 'osonlashtirmoq, yengillashtirmoq',
      definitionEn: 'To make an action or process easier.',
      exampleEn: 'New roads facilitate trade between cities.',
      exampleTranslated: "Yangi yo'llar shaharlar o'rtasidagi savdoni osonlashtiradi.",
    },
  },

  // ============================================================
  // BUSINESS ENGLISH — 25 ta (B1-C1)
  // ============================================================
  {
    word: 'revenue',
    pronunciation: '/ˈrevənuː/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'daromad, tushum',
      definitionEn: 'The money that a business receives from its activities.',
      exampleEn: 'The company increased its revenue last year.',
      exampleTranslated: "Kompaniya o'tgan yili daromadini oshirdi.",
    },
  },
  {
    word: 'invoice',
    pronunciation: '/ˈɪnvɔɪs/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'hisob-faktura',
      definitionEn: 'A document that lists goods or services and their prices to be paid.',
      exampleEn: 'Please send the invoice by the end of the week.',
      exampleTranslated: 'Iltimos, hisob-fakturani hafta oxirigacha yuboring.',
    },
  },
  {
    word: 'negotiate',
    pronunciation: '/nɪˈɡoʊʃieɪt/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'muzokara olib bormoq, kelishmoq',
      definitionEn: 'To talk with others to reach an agreement.',
      exampleEn: 'We need to negotiate a better price with the supplier.',
      exampleTranslated: "Biz yetkazib beruvchi bilan yaxshiroq narx haqida kelishishimiz kerak.",
    },
  },
  {
    word: 'deadline',
    pronunciation: '/ˈdedlaɪn/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'muddat, oxirgi muddat',
      definitionEn: 'The latest time by which something must be finished.',
      exampleEn: 'We must meet the deadline for this project.',
      exampleTranslated: 'Biz bu loyiha muddatiga yetishishimiz shart.',
    },
  },
  {
    word: 'profit',
    pronunciation: '/ˈprɑːfɪt/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'foyda',
      definitionEn: 'The money you gain after costs are taken away.',
      exampleEn: 'The shop made a good profit during the holidays.',
      exampleTranslated: "Do'kon bayramlar davomida yaxshi foyda ko'rdi.",
    },
  },
  {
    word: 'client',
    pronunciation: '/ˈklaɪənt/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'mijoz',
      definitionEn: 'A person or company that pays for services or advice.',
      exampleEn: 'Our client is very happy with the results.',
      exampleTranslated: 'Mijozimiz natijalardan juda mamnun.',
    },
  },
  {
    word: 'budget',
    pronunciation: '/ˈbʌdʒɪt/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'byudjet, mablag\'',
      definitionEn: 'A plan of how much money you have and how you will spend it.',
      exampleEn: 'The marketing budget for this year is limited.',
      exampleTranslated: 'Bu yilgi marketing byudjeti cheklangan.',
    },
  },
  {
    word: 'meeting',
    pronunciation: '/ˈmiːtɪŋ/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Business English',
    uz: {
      translation: 'uchrashuv, yig\'ilish',
      definitionEn: 'An event where people come together to discuss something.',
      exampleEn: 'The meeting starts at ten in the morning.',
      exampleTranslated: "Yig'ilish ertalab soat o'nda boshlanadi.",
    },
  },
  {
    word: 'colleague',
    pronunciation: '/ˈkɑːliːɡ/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'hamkasb',
      definitionEn: 'A person you work with, especially in a profession.',
      exampleEn: 'My colleague helped me finish the report.',
      exampleTranslated: 'Hamkasbim hisobotni tugatishimga yordam berdi.',
    },
  },
  {
    word: 'manager',
    pronunciation: '/ˈmænɪdʒər/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Business English',
    uz: {
      translation: 'menejer, rahbar',
      definitionEn: 'A person who is in charge of a business or a part of it.',
      exampleEn: 'The manager approved our new plan.',
      exampleTranslated: 'Menejer bizning yangi rejamizni tasdiqladi.',
    },
  },
  {
    word: 'employee',
    pronunciation: '/ɪmˈplɔɪiː/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'xodim, ishchi',
      definitionEn: 'A person who works for a company or another person.',
      exampleEn: 'The company has more than fifty employees.',
      exampleTranslated: "Kompaniyada ellikdan ortiq xodim bor.",
    },
  },
  {
    word: 'customer',
    pronunciation: '/ˈkʌstəmər/',
    partOfSpeech: 'noun',
    difficulty: 'A2',
    category: 'Business English',
    uz: {
      translation: 'xaridor, mijoz',
      definitionEn: 'A person who buys goods or services from a shop or business.',
      exampleEn: 'Good service keeps customers coming back.',
      exampleTranslated: 'Yaxshi xizmat xaridorlarni qaytib kelishga undaydi.',
    },
  },
  {
    word: 'salary',
    pronunciation: '/ˈsæləri/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'maosh, oylik',
      definitionEn: 'The money a person receives each month for their work.',
      exampleEn: 'She earns a good salary at her new job.',
      exampleTranslated: 'U yangi ishida yaxshi maosh oladi.',
    },
  },
  {
    word: 'contract',
    pronunciation: '/ˈkɑːntrækt/',
    partOfSpeech: 'noun',
    difficulty: 'B1',
    category: 'Business English',
    uz: {
      translation: 'shartnoma',
      definitionEn: 'A legal written agreement between two or more people.',
      exampleEn: 'Both sides signed the contract yesterday.',
      exampleTranslated: 'Ikkala tomon kecha shartnomani imzoladi.',
    },
  },
  {
    word: 'invest',
    pronunciation: '/ɪnˈvest/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'sarmoya kiritmoq, investitsiya qilmoq',
      definitionEn: 'To put money into a business or project to make a profit.',
      exampleEn: 'They decided to invest in new technology.',
      exampleTranslated: 'Ular yangi texnologiyaga sarmoya kiritishga qaror qilishdi.',
    },
  },
  {
    word: 'expense',
    pronunciation: '/ɪkˈspens/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'xarajat',
      definitionEn: 'The money that you spend on something.',
      exampleEn: 'We need to reduce our monthly expenses.',
      exampleTranslated: 'Biz oylik xarajatlarimizni kamaytirishimiz kerak.',
    },
  },
  {
    word: 'strategy',
    pronunciation: '/ˈstrætədʒi/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'strategiya, reja',
      definitionEn: 'A plan for achieving a goal over a long period.',
      exampleEn: 'The company changed its marketing strategy.',
      exampleTranslated: "Kompaniya marketing strategiyasini o'zgartirdi.",
    },
  },
  {
    word: 'productivity',
    pronunciation: '/ˌproʊdʌkˈtɪvəti/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'samaradorlik, unumdorlik',
      definitionEn: 'The rate at which a person or company produces work or goods.',
      exampleEn: 'Short breaks can improve productivity at work.',
      exampleTranslated: 'Qisqa tanaffuslar ishdagi samaradorlikni oshirishi mumkin.',
    },
  },
  {
    word: 'supplier',
    pronunciation: '/səˈplaɪər/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'yetkazib beruvchi, taʼminotchi',
      definitionEn: 'A company or person that provides goods to a business.',
      exampleEn: 'We found a cheaper supplier for our materials.',
      exampleTranslated: 'Biz materiallarimiz uchun arzonroq yetkazib beruvchi topdik.',
    },
  },
  {
    word: 'launch',
    pronunciation: '/lɔːntʃ/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'ishga tushirmoq, taqdim etmoq',
      definitionEn: 'To start something new, such as a product or a company.',
      exampleEn: 'The company will launch a new product next month.',
      exampleTranslated: 'Kompaniya keyingi oy yangi mahsulotni taqdim etadi.',
    },
  },
  {
    word: 'profitable',
    pronunciation: '/ˈprɑːfɪtəbl/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'foydali, daromadli',
      definitionEn: 'Producing a profit or financial gain.',
      exampleEn: 'The new branch became profitable within a year.',
      exampleTranslated: "Yangi filial bir yil ichida foydali bo'ldi.",
    },
  },
  {
    word: 'shareholder',
    pronunciation: '/ˈʃerhoʊldər/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Business English',
    uz: {
      translation: 'aksiyador',
      definitionEn: 'A person who owns shares in a company.',
      exampleEn: 'The shareholders voted for the new chairman.',
      exampleTranslated: 'Aksiyadorlar yangi rais uchun ovoz berishdi.',
    },
  },
  {
    word: 'entrepreneur',
    pronunciation: '/ˌɑːntrəprəˈnɜːr/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Business English',
    uz: {
      translation: 'tadbirkor',
      definitionEn: 'A person who starts a business and takes financial risks.',
      exampleEn: 'Many young entrepreneurs start with a small idea.',
      exampleTranslated: "Ko'plab yosh tadbirkorlar kichik g'oyadan boshlaydi.",
    },
  },
  {
    word: 'stakeholder',
    pronunciation: '/ˈsteɪkhoʊldər/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Business English',
    uz: {
      translation: 'manfaatdor tomon',
      definitionEn: 'A person or group with an interest in a business or project.',
      exampleEn: 'We informed all stakeholders about the changes.',
      exampleTranslated: "Biz barcha manfaatdor tomonlarni o'zgarishlar haqida xabardor qildik.",
    },
  },
  {
    word: 'efficient',
    pronunciation: '/ɪˈfɪʃnt/',
    partOfSpeech: 'adjective',
    difficulty: 'B2',
    category: 'Business English',
    uz: {
      translation: 'samarali',
      definitionEn: 'Working well without wasting time, money or energy.',
      exampleEn: 'The new system is more efficient than the old one.',
      exampleTranslated: 'Yangi tizim eskisidan ko\'ra samaraliroq.',
    },
  },

  // ============================================================
  // ACADEMIC — 20 ta (B2-C2) — akademik yozuv, linking words
  // ============================================================
  {
    word: 'hypothesis',
    pronunciation: '/haɪˈpɑːθəsɪs/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'gipoteza, faraz',
      definitionEn: 'An idea that is suggested as an explanation but not yet proven.',
      exampleEn: 'The experiment was designed to test the hypothesis.',
      exampleTranslated: 'Tajriba gipotezani sinash uchun ishlab chiqilgan edi.',
    },
  },
  {
    word: 'methodology',
    pronunciation: '/ˌmeθəˈdɑːlədʒi/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'metodologiya, tadqiqot usuli',
      definitionEn: 'The set of methods used in a particular area of study.',
      exampleEn: 'The researchers explained their methodology in detail.',
      exampleTranslated: 'Tadqiqotchilar o\'z metodologiyasini batafsil tushuntirishdi.',
    },
  },
  {
    word: 'thesis',
    pronunciation: '/ˈθiːsɪs/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'dissertatsiya, ilmiy ish',
      definitionEn: 'A long piece of writing based on research for a university degree.',
      exampleEn: 'She is writing her thesis on renewable energy.',
      exampleTranslated: "U qayta tiklanadigan energiya bo'yicha dissertatsiyasini yozyapti.",
    },
  },
  {
    word: 'cite',
    pronunciation: '/saɪt/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'iqtibos keltirmoq, manba sifatida keltirmoq',
      definitionEn: 'To mention a source as evidence in academic writing.',
      exampleEn: 'You must cite every source you use in your essay.',
      exampleTranslated: "Insholaringizda foydalangan har bir manbani keltirishingiz shart.",
    },
  },
  {
    word: 'furthermore',
    pronunciation: '/ˈfɜːrðərmɔːr/',
    partOfSpeech: 'adverb',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'bundan tashqari, qolaversa',
      definitionEn: 'In addition to what has already been said.',
      exampleEn: 'The plan is expensive; furthermore, it may not work.',
      exampleTranslated: "Reja qimmat; bundan tashqari, u ishlamasligi ham mumkin.",
    },
  },
  {
    word: 'moreover',
    pronunciation: '/mɔːrˈoʊvər/',
    partOfSpeech: 'adverb',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'bundan tashqari, ustiga-ustak',
      definitionEn: 'Used to add information that supports a previous statement.',
      exampleEn: 'The method is simple; moreover, it is very effective.',
      exampleTranslated: 'Usul oddiy; bundan tashqari, u juda samarali.',
    },
  },
  {
    word: 'nevertheless',
    pronunciation: '/ˌnevərðəˈles/',
    partOfSpeech: 'adverb',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'shunga qaramay, shunday bo\'lsa-da',
      definitionEn: 'In spite of what has just been said.',
      exampleEn: 'The task was hard; nevertheless, they completed it.',
      exampleTranslated: 'Vazifa qiyin edi; shunga qaramay, ular uni bajarishdi.',
    },
  },
  {
    word: 'analyse',
    pronunciation: '/ˈænəlaɪz/',
    partOfSpeech: 'verb',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'tahlil qilmoq',
      definitionEn: 'To examine something carefully to understand it.',
      exampleEn: 'Scientists analyse the data before making conclusions.',
      exampleTranslated: "Olimlar xulosa chiqarishdan oldin ma'lumotlarni tahlil qiladi.",
    },
  },
  {
    word: 'theory',
    pronunciation: '/ˈθɪəri/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'nazariya',
      definitionEn: 'A set of ideas that explains how or why something happens.',
      exampleEn: 'His theory changed the way we understand the universe.',
      exampleTranslated: "Uning nazariyasi olamni tushunish tarzimizni o'zgartirdi.",
    },
  },
  {
    word: 'evidence',
    pronunciation: '/ˈevɪdəns/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'dalil, isbot',
      definitionEn: 'Facts or signs that show that something is true.',
      exampleEn: 'There is strong evidence to support this idea.',
      exampleTranslated: "Bu g'oyani qo'llab-quvvatlovchi kuchli dalil bor.",
    },
  },
  {
    word: 'conclusion',
    pronunciation: '/kənˈkluːʒn/',
    partOfSpeech: 'noun',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'xulosa',
      definitionEn: 'A decision or opinion reached after thinking carefully.',
      exampleEn: 'The study came to an interesting conclusion.',
      exampleTranslated: 'Tadqiqot qiziqarli xulosaga keldi.',
    },
  },
  {
    word: 'assumption',
    pronunciation: '/əˈsʌmpʃn/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'taxmin, faraz',
      definitionEn: 'Something that you accept as true without proof.',
      exampleEn: 'The argument is based on a false assumption.',
      exampleTranslated: "Bahs noto'g'ri farazga asoslangan.",
    },
  },
  {
    word: 'interpret',
    pronunciation: '/ɪnˈtɜːrprət/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'talqin qilmoq, izohlamoq',
      definitionEn: 'To explain the meaning of something.',
      exampleEn: 'Different readers may interpret the poem in different ways.',
      exampleTranslated: "Turli o'quvchilar she'rni turlicha talqin qilishi mumkin.",
    },
  },
  {
    word: 'framework',
    pronunciation: '/ˈfreɪmwɜːrk/',
    partOfSpeech: 'noun',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'asos, tuzilma, ramka',
      definitionEn: 'A basic structure of ideas used to plan or understand something.',
      exampleEn: 'The author presents a clear theoretical framework.',
      exampleTranslated: 'Muallif aniq nazariy asosni taqdim etadi.',
    },
  },
  {
    word: 'empirical',
    pronunciation: '/ɪmˈpɪrɪkl/',
    partOfSpeech: 'adjective',
    difficulty: 'C2',
    category: 'Academic',
    uz: {
      translation: 'empirik, tajribaga asoslangan',
      definitionEn: 'Based on observation or experiment rather than theory.',
      exampleEn: 'The claim is supported by strong empirical evidence.',
      exampleTranslated: "Da'vo kuchli empirik dalillar bilan qo'llab-quvvatlanadi.",
    },
  },
  {
    word: 'paradigm',
    pronunciation: '/ˈpærədaɪm/',
    partOfSpeech: 'noun',
    difficulty: 'C2',
    category: 'Academic',
    uz: {
      translation: 'paradigma, namuna, model',
      definitionEn: 'A typical example or model of how something works or is thought about.',
      exampleEn: 'The discovery led to a new scientific paradigm.',
      exampleTranslated: 'Kashfiyot yangi ilmiy paradigmaga olib keldi.',
    },
  },
  {
    word: 'coherent',
    pronunciation: '/koʊˈhɪrənt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'izchil, mantiqiy bog\'langan',
      definitionEn: 'Logical and well organised so that it is easy to understand.',
      exampleEn: 'A good essay must present a coherent argument.',
      exampleTranslated: 'Yaxshi insho izchil dalilni taqdim etishi kerak.',
    },
  },
  {
    word: 'derive',
    pronunciation: '/dɪˈraɪv/',
    partOfSpeech: 'verb',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'olmoq, kelib chiqmoq',
      definitionEn: 'To get or obtain something from a source.',
      exampleEn: 'Many English words derive from Latin.',
      exampleTranslated: "Ko'plab ingliz so'zlari lotin tilidan kelib chiqqan.",
    },
  },
  {
    word: 'subsequent',
    pronunciation: '/ˈsʌbsɪkwənt/',
    partOfSpeech: 'adjective',
    difficulty: 'C1',
    category: 'Academic',
    uz: {
      translation: 'keyingi, navbatdagi',
      definitionEn: 'Coming after something else in time.',
      exampleEn: 'The idea was developed in subsequent chapters.',
      exampleTranslated: "G'oya keyingi boblarda rivojlantirildi.",
    },
  },
  {
    word: 'whereas',
    pronunciation: '/ˌwerˈæz/',
    partOfSpeech: 'conjunction',
    difficulty: 'B2',
    category: 'Academic',
    uz: {
      translation: 'holbuki, ... bo\'lsa esa',
      definitionEn: 'Used to compare two different facts or situations.',
      exampleEn: 'Some students prefer reading, whereas others prefer listening.',
      exampleTranslated: "Ba'zi o'quvchilar o'qishni afzal ko'rsa, boshqalari tinglashni yoqtiradi.",
    },
  },
]
